### ISSUE TITLE
Create models and scrapy project

### ISSUE THREAD

**Issue by paulcollinsiii** [pytube/scraper#1]
Initial project has been created but we don't have items defined.

The current data (e.g. https://github.com/pytube/pyvideo-data/blob/master/data/djangocon-2015/videos/adding-geo-into-your-django-by-corryn-smith.json) has a format that is already used in pytube. We need to mirror this format so that items generated by scrapy are easy to ingest in pytube. 

This issue needs to be finished before other scrapers can be completed however initial work on scrapers such as crawling the pages and getting the relevant sections is NOT blocked.

**Comment by robalford** [comment]
Going to work on defining items.

**Comment by paulcollinsiii** [comment]
closed by #10 and #14
