### ISSUE TITLE
Create an Item Pipeline

### ISSUE THREAD

**Issue by piotrbulinski** [pytube/scraper#11]
We need an [Item Pipeline](http://doc.scrapy.org/en/1.1/topics/item-pipeline.html), so we can generate a valid PyVideo directory structure for an event.

[Example directory structure](https://github.com/pyvideo/pyvideo-data/tree/master/data/twitter-university-2014)

**Comment by macro1** [comment]
I can take a stab at this.

**Comment by macro1** [comment]
@piotrbulinski: This is where I'm at right now... I'm not sure how we should fit the category meta data into it.

https://github.com/pytube/scraper/compare/master...macro1:pipeline

**Comment by piotrbulinski** [comment]
@macro1 will you continue working on that or can I take over and add the changes as discussed earlier?

**Comment by macro1** [comment]
You can grab it if you like

**Comment by piotrbulinski** [comment]
That's resolved with #17
