### ISSUE TITLE
scraper for djangocon eu 2015 talks.

### ISSUE THREAD

**Issue by ne0zen** [pytube/scraper#22]
schedule link for this conference in #3 doesn't really look like any of the other DjangoCon EU pages we might need to hack up a scraper for each one.  Grabbing the talks from the most recent one (that doesn't use an opaque video hosting service) seems like a reasonable thing to do.  I'll try to leverage the utils @piotrbulinski has built up already where possible.

**Comment by paulcollinsiii** [comment]
Okay I'm working up a scraper for this right now. Vimeo has it's own API as well so I'm digging through their docs and will get something together for it similar to the youtube scraper.

**Comment by paulcollinsiii** [comment]
Fixed in #27
